questions = [
    
    /* ESSENTIALISME ************************************************ */
    {
        question: "« On ne naît pas femme, on le devient ».",
        answer: 0,
        cause: -10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Dans l'espèce humaine, l'homosexualité est autant naturelle que l'hétérosexualité.",
        answer: 0,
        cause: -10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: 0,
        bonus: ""
    },
    {
        question: "Les différences de traitements et de qualité de vie dans notre société montrent que le racisme est encore très présent.",
        answer: 0,
        cause: -10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les sciences dites « dures » sont subjectives et reproduisent les structures sociales de notre société.",
        answer: 0,
        cause: -10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les catégories « homme » et « femme » sont des constructions sociales qu'il convient de dépasser.",
        answer: 0,
        cause: -10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "La place des hommes et des femmes dans la société peut-être en partie expliquée par la biologie.",
        answer: 0,
        cause: 10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Certains traits de caractère sont féminins alors que d'autre sont masculins.",
        answer: 0,
        cause: 10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les agressions sexuelles sont en partie causées par les pulsions naturelles des hommes.",
        answer: 0,
        cause: 10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Un enfant doit être éduqué par son père et sa mère biologique car c'est le modèle naturel.",
        answer: 0,
        cause: 10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "La biologie permet d'expliquer les différences de comportement entre différents groupes ethniques.",
        answer: 0,
        cause: 10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les personnes transgenres ne seront jamais vraiment du genre qu’ils veulent atteindre.",
        answer: 0,
        cause: 10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les membres d'une même nation ou d'une même culture ont des traits caractéristiques immuables qui les définissent.",
        answer: 0,
        cause: 10,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    
    /* NATIONALISME ************************************************* */
    {
        question: "À terme, les frontières doivent être supprimées.",
        answer: 0,
        cause: 0,
        boundaries: -10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Il faut défendre ses idéaux, même si cela revient à trahir son pays.",
        answer: 0,
        cause: 0,
        boundaries: -10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Mon pays doit payer pour réparer les dégâts causés par les crimes qu'il a commis à l'étranger.",
        answer: 0,
        cause: 0,
        boundaries: -10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Si les conditions et les normes sont compatibles, il faut supprimer les taxes pour les produits étrangers.",
        answer: 0,
        cause: 0,
        boundaries: -10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Le chauvinisme pendant les compétitions sportives est acceptable.",
        answer: 0,
        cause: 0,
        boundaries: 10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les citoyens doivent être prioritaire par rapport aux étrangers.",
        answer: 0,
        cause: 0,
        boundaries: 10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les valeurs de mon pays sont supérieurs à celles des autres.",
        answer: 0,
        cause: 0,
        boundaries: 10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Le multiculturalisme est un danger.",
        answer: 0,
        cause: 0,
        boundaries: 10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Un bon citoyen est patriote.",
        answer: 0,
        cause: 0,
        boundaries: 10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Il est légitime pour un pays d'intervenir militairement à l'étranger pour défendre ses intérêts.",
        answer: 0,
        cause: 0,
        boundaries: 10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Il faut enseigner l'Histoire d'une façon qui permet de créer un sentiment d'appartenance à la nation.",
        answer: 0,
        cause: 0,
        boundaries: 10,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    
    /* ECONOMIE ***************************************************** */
    
    {
        question: "Les moyens de production ne devraient pas pouvoir être des propriétés privées.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: -10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Une entreprise privée employant des salariés commet un acte comparable au vol.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: -10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Il est important que la santé reste majoritairement publique.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: -10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "L'énergie et les infrastructures de transport doivent être publique.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: -10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les décisions prisent par les actionnaires des entreprises privés ont des effets globalement négatifs sur la société.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: -10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "L'accès à un bien ne doit pas être déterminé par son prix mais par le besoin d'une personne.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: -10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Le marché du travail est une aliénation.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: -10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "La recherche de son propre profit est saine pour l'économie.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "C'est le mérite qui explique la différence de richesse entre deux personnes.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Actuellement, un salarié seul est libre de ses choix lors de la signature de son contrat avec son future employeur.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Il n'y a pas de problème à ce que les écoles et les universités puissent être privée.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les délocalisations sont un mal nécessaire pour améliorer la production.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Il est normal qu'il y ait des riches et des pauvres.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les marchés s’autorégulent quand ils ne sont pas entravés.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 10,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    
    /* SOCIETE ****************************************************** */
    
    {
        question: "Toute tradition doit pouvoir être remise en question.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: -10,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Je n’ai aucun problème avec le fait que d’autres langues officielles soient ajoutées dans la constitution de mon pays.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: -10,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Il faut supprimer le mariage.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: -10,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les homosexuelles n’ont pas à avoir une égalité de traitement avec les hétérosexuelles en ce qui concerne le mariage, la filiation, l’adoption ou la procréation.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 10,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Dans certaines conditions, la peine de mort est justifiée.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 10,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    
    /* ECOLOGIE ***************************************************** */
    
    {
        question: "Il n’est pas acceptable que les actions humaines entraînent des extinctions d’espèces.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: -10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Les OGM doivent être interdits en dehors de la recherche.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: -10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Le réchauffement climatique doit être combattu.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: -10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Nous devons accepter de changer notre mode de consommation pour limiter l’exploitation de la nature.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: -10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Il est important de maintenir la biodiversité dans nos aliments, même si cela est moins efficace.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: -10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "A long terme, il faut coloniser les autres corps du système solaire.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Transformer durablement les écosystèmes pour augmenter la qualité de vie des humains est légitime.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Il faut massivement investir dans la recherche pour améliorer la productivité.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Le transhumanisme sera bénéfique car il permettra d’améliorer nos capacités.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    {
        question: "Le nucléaire, quand il est bien entretenu, est une bonne source d’énergie.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 10,
        rights: 0,
        strategy:0,
        bonus: ""
    },
    
    /* LIBERTAIRE *************************************************** */
    
    {
        question: "La liberté d’expression doit être garantie, même pour les personnes incitant à commettre des crimes.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: -10,
        strategy:0,
        bonus: ""
    },
    {
        question: "Tout Etat exerce une oppression sur son peuple.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: -10,
        strategy:0,
        bonus: ""
    },
    {
        question: "Tout citoyen devrait être en mesure d’utiliser Internet de façon anonyme.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: -10,
        strategy:0,
        bonus: ""
    },
    {
        question: "L’État ne devrait pas intervenir dans l’économie.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: -10,
        strategy:0,
        bonus: ""
    },
    {
        question: "La démocratie ne peut pas fonctionner et seule une élite formée est capable de diriger un pays correctement.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 10,
        strategy:0,
        bonus: ""
    },
    {
        question: "Le but du système judiciaire est de punir ceux qui ont enfreint les règles.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 10,
        strategy:0,
        bonus: ""
    },
    {
        question: "La surveillance permet de garantir les libertés.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 10,
        strategy:0,
        bonus: ""
    },
    
    /* STRATEGIE **************************************************** */
    
    {
        question: "Il est possible de renverser un système depuis l'intérieur.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: 10,
        bonus: ""
    },
    {
        question: "La violence n'est jamais une solution.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: 10,
        bonus: ""
    },
    {
        question: "Changer le système de façon radicale est contre-productif. Il faut plutôt transformer la société progressivement.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: 10,
        bonus: ""
    },
    {
        question: "Les révolutions finissent toujours mal.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: 10,
        bonus: ""
    },
    {
        question: "Il faut toujours militer dans le strict respect de la loi.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: 10,
        bonus: ""
    },
    {
        question: "Les élections sont inutiles car elles permettent au système de se maintenir.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: -10,
        bonus: ""
    },
    {
        question: "Militer au sein des institutions politiques en place n’est pas suffisant pour transformer la société.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: -10,
        bonus: ""
    },
    {
        question: "« Le pouvoir ne doit pas être conquis, il doit être détruit ».",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: -10,
        bonus: ""
    },
    
    /* BONUS ******************************************************** */
    
    {
        question: "C’est un petit groupe qui contrôle secrètement et consciemment le monde.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: "cpl"
    },
    {
        question: "Ma religion doit se diffuser le plus largement possible.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: "rel"
    },
    {
        question: "Une bonne politique, c’est une politique pragmatique et sans idéologie.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: "pra"
    },
    {
        question: "Il faut mettre en place une monarchie afin de fédérer le peuple et préserver notre souveraineté.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy:0,
        bonus: "roy"
    },
    {
        question: "Les humains ne doivent plus manger ou exploiter les animaux vivants.",
        answer: 0,
        cause: 0,
        boundaries: 0,
        economy: 0,
        society: 0,
        ecosystem: 0,
        rights: 0,
        strategy: 0,
        bonus: "veg"
    }
];
